name: CI - format & lint & typecheck

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    format:
        name: Format
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.20.0"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci --legacy-peer-deps --no-audit --no-fund

            - name: Run Prettier (format)
              run: npm run format

            - name: Check if formatting changed files
              run: |
                  if [ -n "$(git status --porcelain)" ]; then
                    echo "Files need formatting. Please run 'npm run format' locally and commit.";
                    git --no-pager status --porcelain
                    exit 1
                  fi

    lint:
        name: Lint
        runs-on: ubuntu-latest
        needs: format
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.20.0"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci --legacy-peer-deps --no-audit --no-fund

            - name: Run ESLint (auto-fix)
              run: npm run lint:fix

            - name: Check if linting changed files
              run: |
                  if [ -n "$(git status --porcelin)" ]; then
                    echo "Files need linting fixes. Please run 'npm run lint:fix' locally and commit.";
                    git --no-pager status --porcelain
                    exit 1
                  fi

    typecheck:
        name: Typecheck
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.20.0"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci --legacy-peer-deps --no-audit --no-fund

            - name: Run TypeScript check
              run: npx tsc --noEmit
